apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-desktop-lxde-vnc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-desktop-lxde-vnc
  template:
    metadata:
      labels:
        app: ubuntu-desktop-lxde-vnc
    spec:
      containers:
      - image: hwdsl2/ipsec-vpn-server
        name: ubuntu-desktop-lxde-vnc
        ports:
        - containerPort: 80 1701 443 22 500 4500
